#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AForm.Forms.AReport
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="real")]
	public partial class DataClassesSalesReportDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    #endregion
		
		public DataClassesSalesReportDataContext() : 
				base(global::AForm.Properties.Settings.Default.realConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSalesReportDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSalesReportDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSalesReportDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesSalesReportDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tempdata_for_salereport> tempdata_for_salereport
		{
			get
			{
				return this.GetTable<tempdata_for_salereport>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tempdata_for_salereport")]
	public partial class tempdata_for_salereport
	{
		
		private System.Nullable<decimal> _sumSale;
		
		private System.Nullable<int> _kolSale;
		
		private string _nTerritoryShort;
		
		private System.Nullable<decimal> _Profit;
		
		private System.Nullable<decimal> _Profittrunsport;
		
		private System.Nullable<int> _MonthSale;
		
		private System.Nullable<int> _YearSale;
		
		private string _nTypeTov;
		
		private string _NameGroup;
		
		private string _nAgent;
		
		private string _nPodgroup;
		
		private string _nKontr;
		
		private string _tm_name;
		
		private string _Oblast;
		
		private string _Segment;
		
		private string _TovLine;
		
		private string _TOV_NAME;
		
		private string _in_tax;
		
		private string _forder;
		
		private string _nCategory;
		
		private System.Nullable<int> _iduser;
		
		private string _n_tov;
		
		private string _id_tov_oem;
		
		private System.Nullable<int> _id_tov;
		
		private string _company_name;
		
		private System.Nullable<decimal> _litrage_sumval;
		
		private string _clustername;
		
		public tempdata_for_salereport()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sumSale", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> sumSale
		{
			get
			{
				return this._sumSale;
			}
			set
			{
				if ((this._sumSale != value))
				{
					this._sumSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kolSale", DbType="Int")]
		public System.Nullable<int> kolSale
		{
			get
			{
				return this._kolSale;
			}
			set
			{
				if ((this._kolSale != value))
				{
					this._kolSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nTerritoryShort", DbType="VarChar(50)")]
		public string nTerritoryShort
		{
			get
			{
				return this._nTerritoryShort;
			}
			set
			{
				if ((this._nTerritoryShort != value))
				{
					this._nTerritoryShort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profit", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Profit
		{
			get
			{
				return this._Profit;
			}
			set
			{
				if ((this._Profit != value))
				{
					this._Profit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profittrunsport", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Profittrunsport
		{
			get
			{
				return this._Profittrunsport;
			}
			set
			{
				if ((this._Profittrunsport != value))
				{
					this._Profittrunsport = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthSale", DbType="Int")]
		public System.Nullable<int> MonthSale
		{
			get
			{
				return this._MonthSale;
			}
			set
			{
				if ((this._MonthSale != value))
				{
					this._MonthSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearSale", DbType="Int")]
		public System.Nullable<int> YearSale
		{
			get
			{
				return this._YearSale;
			}
			set
			{
				if ((this._YearSale != value))
				{
					this._YearSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nTypeTov", DbType="VarChar(128)")]
		public string nTypeTov
		{
			get
			{
				return this._nTypeTov;
			}
			set
			{
				if ((this._nTypeTov != value))
				{
					this._nTypeTov = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameGroup", DbType="VarChar(128)")]
		public string NameGroup
		{
			get
			{
				return this._NameGroup;
			}
			set
			{
				if ((this._NameGroup != value))
				{
					this._NameGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nAgent", DbType="VarChar(255)")]
		public string nAgent
		{
			get
			{
				return this._nAgent;
			}
			set
			{
				if ((this._nAgent != value))
				{
					this._nAgent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nPodgroup", DbType="VarChar(255)")]
		public string nPodgroup
		{
			get
			{
				return this._nPodgroup;
			}
			set
			{
				if ((this._nPodgroup != value))
				{
					this._nPodgroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nKontr", DbType="VarChar(255)")]
		public string nKontr
		{
			get
			{
				return this._nKontr;
			}
			set
			{
				if ((this._nKontr != value))
				{
					this._nKontr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tm_name", DbType="VarChar(128)")]
		public string tm_name
		{
			get
			{
				return this._tm_name;
			}
			set
			{
				if ((this._tm_name != value))
				{
					this._tm_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oblast", DbType="VarChar(128)")]
		public string Oblast
		{
			get
			{
				return this._Oblast;
			}
			set
			{
				if ((this._Oblast != value))
				{
					this._Oblast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segment", DbType="VarChar(128)")]
		public string Segment
		{
			get
			{
				return this._Segment;
			}
			set
			{
				if ((this._Segment != value))
				{
					this._Segment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TovLine", DbType="VarChar(128)")]
		public string TovLine
		{
			get
			{
				return this._TovLine;
			}
			set
			{
				if ((this._TovLine != value))
				{
					this._TovLine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOV_NAME", DbType="VarChar(128)")]
		public string TOV_NAME
		{
			get
			{
				return this._TOV_NAME;
			}
			set
			{
				if ((this._TOV_NAME != value))
				{
					this._TOV_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_in_tax", DbType="VarChar(2)")]
		public string in_tax
		{
			get
			{
				return this._in_tax;
			}
			set
			{
				if ((this._in_tax != value))
				{
					this._in_tax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_forder", DbType="VarChar(15)")]
		public string forder
		{
			get
			{
				return this._forder;
			}
			set
			{
				if ((this._forder != value))
				{
					this._forder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nCategory", DbType="VarChar(128)")]
		public string nCategory
		{
			get
			{
				return this._nCategory;
			}
			set
			{
				if ((this._nCategory != value))
				{
					this._nCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iduser", DbType="Int")]
		public System.Nullable<int> iduser
		{
			get
			{
				return this._iduser;
			}
			set
			{
				if ((this._iduser != value))
				{
					this._iduser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n_tov", DbType="VarChar(255)")]
		public string n_tov
		{
			get
			{
				return this._n_tov;
			}
			set
			{
				if ((this._n_tov != value))
				{
					this._n_tov = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tov_oem", DbType="VarChar(128)")]
		public string id_tov_oem
		{
			get
			{
				return this._id_tov_oem;
			}
			set
			{
				if ((this._id_tov_oem != value))
				{
					this._id_tov_oem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tov", DbType="Int")]
		public System.Nullable<int> id_tov
		{
			get
			{
				return this._id_tov;
			}
			set
			{
				if ((this._id_tov != value))
				{
					this._id_tov = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_name", DbType="VarChar(128)")]
		public string company_name
		{
			get
			{
				return this._company_name;
			}
			set
			{
				if ((this._company_name != value))
				{
					this._company_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_litrage_sumval", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> litrage_sumval
		{
			get
			{
				return this._litrage_sumval;
			}
			set
			{
				if ((this._litrage_sumval != value))
				{
					this._litrage_sumval = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clustername", DbType="VarChar(255)")]
		public string clustername
		{
			get
			{
				return this._clustername;
			}
			set
			{
				if ((this._clustername != value))
				{
					this._clustername = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
