//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogic.Model.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyEntity
    {
        public int idCompanyEntity { get; set; }
        public int idCompany { get; set; }
        public string nEntity { get; set; }
        public int idCompanyTemp { get; set; }
        public int fUr { get; set; }
        public int fPlace { get; set; }
        public int fSP { get; set; }
        public int fTD { get; set; }
        public int fTP { get; set; }
        public int iKontr { get; set; }
    }
}
