//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogic.Model.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decree
    {
        public int IdDecree { get; set; }
        public System.DateTime DateDecree { get; set; }
        public string nDecree { get; set; }
        public string Content { get; set; }
        public string NomDecree { get; set; }
        public string TitleDecree { get; set; }
        public string nTypeSign { get; set; }
        public string nSign { get; set; }
    }
}
