//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogic.Model.EntityFrame
{
    using System;
    
    public partial class EordrUser
    {
        public Nullable<int> idkontr { get; set; }
        public string n_kontr { get; set; }
        public Nullable<int> category { get; set; }
        public string email { get; set; }
        public string contactname { get; set; }
        public string contacttel { get; set; }
        public string login_www { get; set; }
        public string pass_www { get; set; }
        public Nullable<int> idagent { get; set; }
        public string agentfio { get; set; }
        public string agenttelcorp { get; set; }
        public string agenttelvn { get; set; }
        public string agentemail { get; set; }
        public string emailcredit { get; set; }
        public string emailcontract { get; set; }
        public short CountAccesseOrder { get; set; }
        public string emailAccessRegion { get; set; }
        public int SchoolTPAdmin { get; set; }
        public int SchoolTPUser { get; set; }
        public int ExpandedInfo { get; set; }
        public Nullable<decimal> id_torg { get; set; }
        public int fneedoffer { get; set; }
        public int idconvoffert { get; set; }
        public Nullable<int> flpr { get; set; }
    }
}
