//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogic.Model.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogeOrder
    {
        public int idRow { get; set; }
        public int idKontr { get; set; }
        public System.DateTime DateAction { get; set; }
        public short idTypeAction { get; set; }
        public string ContentAction { get; set; }
        public byte fSendInfo { get; set; }
        public Nullable<int> idtypedoc { get; set; }
        public string iddoc { get; set; }
        public string NameUser { get; set; }
    }
}
