//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogic.Model.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class rKontrDecree
    {
        public int IdKontrDecree { get; set; }
        public int IdDecree { get; set; }
        public int IdKontr { get; set; }
        public bool fDossier { get; set; }
        public bool fSee { get; set; }
    }
}
