//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogic.Model.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class sAutoDelivery
    {
        public int idAuto { get; set; }
        public string nAuto { get; set; }
        public Nullable<int> Tonnage { get; set; }
        public Nullable<int> Volume { get; set; }
        public string RegNumber { get; set; }
        public int OurAuto { get; set; }
        public Nullable<decimal> idDriverDefault { get; set; }
        public int idStatus { get; set; }
        public int Pallet { get; set; }
        public int EuroPalet { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string PtsNum { get; set; }
        public Nullable<System.DateTime> PtsDate { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> idClass { get; set; }
        public Nullable<int> KmTarif { get; set; }
    }
}
