//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogic.Model.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class sChildren
    {
        public decimal idKontr { get; set; }
        public string nChild { get; set; }
        public int idChild { get; set; }
        public System.DateTime DateBirth { get; set; }
        public string Comment { get; set; }
    
        public virtual spr_kontr spr_kontr { get; set; }
    }
}
