//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogic.Model.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class sLogTypeAction
    {
        public int idTypeAction { get; set; }
        public string nTypeAction { get; set; }
        public byte fNeedForMail { get; set; }
        public string SendTo { get; set; }
    }
}
