//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogic.Model.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class spr_kontr
    {
        public spr_kontr()
        {
            this.sChildren = new HashSet<sChildren>();
        }
    
        public decimal id_kontr { get; set; }
        public string n_kontr { get; set; }
        public string n_kontr_full { get; set; }
        public string n_kontr_short { get; set; }
        public string n_board { get; set; }
        public string adress_ur { get; set; }
        public string adress_fact { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string tel3 { get; set; }
        public string tel4 { get; set; }
        public string tel5 { get; set; }
        public string el_mail { get; set; }
        public string inn { get; set; }
        public string okonh { get; set; }
        public string okpo { get; set; }
        public string n_boss { get; set; }
        public string n_gl_buh { get; set; }
        public string n_cash { get; set; }
        public Nullable<decimal> id_agent { get; set; }
        public Nullable<decimal> id_torg { get; set; }
        public Nullable<decimal> id_firm { get; set; }
        public Nullable<decimal> in_tax_def { get; set; }
        public Nullable<short> id_region { get; set; }
        public Nullable<decimal> id_road { get; set; }
        public Nullable<decimal> t_serv { get; set; }
        public Nullable<byte> id_cond { get; set; }
        public string faice { get; set; }
        public byte seller_bayer { get; set; }
        public Nullable<byte> employer { get; set; }
        public byte agent { get; set; }
        public byte bank { get; set; }
        public byte mol { get; set; }
        public byte firma { get; set; }
        public byte investor_shareholder { get; set; }
        public Nullable<byte> ind_business { get; set; }
        public Nullable<byte> torg { get; set; }
        public Nullable<decimal> srok_kred { get; set; }
        public string name_user { get; set; }
        public decimal id_user { get; set; }
        public Nullable<decimal> sql_id { get; set; }
        public Nullable<decimal> id_post { get; set; }
        public Nullable<byte> gr_compare { get; set; }
        public Nullable<byte> group_inv { get; set; }
        public Nullable<System.DateTime> last_compare { get; set; }
        public byte compare { get; set; }
        public string commentary { get; set; }
        public Nullable<short> kontr_group { get; set; }
        public Nullable<byte> sort_group { get; set; }
        public byte seller_bayer_10 { get; set; }
        public Nullable<short> driver { get; set; }
        public Nullable<byte> category { get; set; }
        public string kpp { get; set; }
        public Nullable<byte> wholesale { get; set; }
        public Nullable<byte> delivery { get; set; }
        public string login_www { get; set; }
        public string pass_www { get; set; }
        public Nullable<short> id_level { get; set; }
        public Nullable<short> update_price { get; set; }
        public Nullable<decimal> per_discount { get; set; }
        public short kol_n { get; set; }
        public short id_filial { get; set; }
        public short filial { get; set; }
        public Nullable<decimal> id_type_tov { get; set; }
        public string svid_nomer { get; set; }
        public string svid_vidano { get; set; }
        public decimal id_direct { get; set; }
        public string n_kontr_title { get; set; }
        public byte autolink { get; set; }
        public string ogrn { get; set; }
        public Nullable<System.DateTime> b_day { get; set; }
        public Nullable<decimal> m_truck { get; set; }
        public Nullable<decimal> v_truck { get; set; }
        public Nullable<short> post_cat { get; set; }
        public Nullable<byte> salary_incl { get; set; }
        public Nullable<byte> salary_type { get; set; }
        public byte ticket_cond { get; set; }
        public Nullable<decimal> ticket_holder { get; set; }
        public Nullable<byte> id_stamp { get; set; }
        public Nullable<int> pasport { get; set; }
        public string receipt_pasport { get; set; }
        public string series_pasport { get; set; }
        public Nullable<int> kred_sum { get; set; }
        public string driver_acc { get; set; }
        public Nullable<int> kred_type { get; set; }
        public Nullable<int> kder_sum_kontr { get; set; }
        public Nullable<byte> time_invoice { get; set; }
        public Nullable<byte> k_rate { get; set; }
        public string Job { get; set; }
        public string Spec { get; set; }
        public string id_ekontr { get; set; }
        public string el_mail_corporate { get; set; }
        public string print_form { get; set; }
        public short sfInDelivery { get; set; }
        public string abc { get; set; }
        public Nullable<long> icqNumber { get; set; }
        public byte idCondEmpl { get; set; }
        public string location { get; set; }
        public Nullable<byte> print_translate { get; set; }
        public byte Retail { get; set; }
        public string abc_estimate { get; set; }
        public byte presense_inn { get; set; }
        public byte presense_svid { get; set; }
        public int idTownship { get; set; }
        public int presense_pasport { get; set; }
        public string n_lpr { get; set; }
        public string tel_lpr { get; set; }
        public byte buy_agent { get; set; }
        public Nullable<short> fOrder { get; set; }
        public string pseudonym { get; set; }
        public string bigcomment { get; set; }
        public int idFond { get; set; }
        public byte supplier { get; set; }
        public byte SupplierService { get; set; }
        public byte f1c { get; set; }
        public string storekeeper { get; set; }
        public string nbossr { get; set; }
        public byte firmfor1c { get; set; }
        public byte PassWithCar { get; set; }
        public short TNInDelivery { get; set; }
        public string PostOfficeBox { get; set; }
        public byte fTransportCompany { get; set; }
        public Nullable<short> fPraisImag { get; set; }
        public Nullable<int> RateCompareMM { get; set; }
        public string latitube { get; set; }
        public string longitube { get; set; }
        public decimal PercentForBonuses { get; set; }
        public short fNotIntegrationNakl { get; set; }
        public string nPostForContract { get; set; }
        public Nullable<short> fNewSaleContractForCash { get; set; }
        public string prefix { get; set; }
        public Nullable<short> CountAccesseOrder { get; set; }
        public string SexBossFoContract { get; set; }
        public int TypeDeliveryDef { get; set; }
        public int FederalImag { get; set; }
        public Nullable<short> fNotUsePriceRec { get; set; }
        public Nullable<System.DateTime> svidDate { get; set; }
        public Nullable<int> idSystemTax { get; set; }
        public Nullable<int> idFirmOil { get; set; }
        public short fneedunload { get; set; }
        public short fNotDivision { get; set; }
        public Nullable<short> idTypePayDef { get; set; }
        public Nullable<int> TimeReaction { get; set; }
        public byte fCustomer { get; set; }
        public byte fSupplier { get; set; }
        public byte fEconomicEntity { get; set; }
        public byte fPointOfStorage { get; set; }
        public byte fWorkWithOil { get; set; }
        public byte fWorkWithAutoParts { get; set; }
        public byte fNeedTTNInDelivery { get; set; }
        public int idStatusLifeCycleCust { get; set; }
        public byte fCanNotEditTovDoc { get; set; }
    
        public virtual ICollection<sChildren> sChildren { get; set; }
    }
}
