//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogic.Model.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabel
    {
        public int id_row { get; set; }
        public decimal id_kontr { get; set; }
        public Nullable<System.DateTime> time_end { get; set; }
        public System.DateTime time_start { get; set; }
        public short type_row { get; set; }
        public string commentary { get; set; }
        public Nullable<short> id_online { get; set; }
        public string id_pc { get; set; }
    }
}
