//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALogic.Model.EntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class tookBonus
    {
        public int id { get; set; }
        public string nomDoc { get; set; }
        public string IdDoc { get; set; }
        public bool status { get; set; }
        public System.DateTime modDate { get; set; }
    }
}
